services:

  Dawid\CronBundle\CronJobRunner\JobScheduler:
    class: 'Dawid\CronBundle\CronJobRunner\JobScheduler'
    public: false

  Dawid\CronBundle\CronJobRunner\CommandRunner:
    class: 'Dawid\CronBundle\CronJobRunner\CommandRunner'
    public: false
    arguments:
      $kernel: '@kernel'

  Dawid\CronBundle\CronJobRunner\Cron:
    class: 'Dawid\CronBundle\CronJobRunner\Cron'
    public: false
    arguments:
      $commandRunner: '@Dawid\CronBundle\CronJobRunner\CommandRunner'
      $jobScheduler: '@Dawid\CronBundle\CronJobRunner\JobScheduler'

  Dawid\CronBundle\Command\CronRunnerCommand:
    class: 'Dawid\CronBundle\Command\CronRunnerCommand'
    tags:
      - { name: 'console.command', command: 'cron:run' }
    arguments:
      $runner: '@Dawid\CronBundle\CronJobRunner\Cron'
      $logger: '@logger'

  Dawid\CronBundle\CronJobRunner\CronJobRegistry:
    class: 'Dawid\CronBundle\CronJobRunner\CronJobRegistry'
    arguments:
      - !tagged_iterator { tag: 'cron.job' }

  Dawid\CronBundle\CronJobRunner\CronJobRegistryInterface:
    class: '@Dawid\CronBundle\CronJobRunner\CronJobRegistry'

  Dawid\CronBundle\CronJobRunnerInterface:
    tags: [ 'cron.job' ]
