services:

  Dawid\CronBundle\CronJobRunner\JobScheduler:
    class: 'Dawid\CronBundle\CronJobRunner\JobScheduler'
    public: false

  Dawid\CronBundle\Command\CronRunnerCommand:
    class: 'Dawid\CronBundle\Command\CronRunnerCommand'
    tags:
      - { name: 'console.command', command: 'cron:run' }
    arguments:
      $runner: '@Dawid\CronBundle\CronJobRunner\Cron'
      $logger: '@logger'

  cron.job_registry.tagged_services:
    class: 'Dawid\CronBundle\CronJobRunner\CronJobRegistry'
    arguments:
      - !tagged_iterator { tag: 'cron.job' }

  Dawid\CronBundle\CronJobRunner\CronJobRegistryInterface:
    class: '@cron.job_registry.tagged_services'

  Dawid\CronBundle\CronJobRunner\Cron:
    class: 'Dawid\CronBundle\CronJobRunner\Cron'
    public: false
    arguments:
      $jobScheduler: '@Dawid\CronBundle\CronJobRunner\CronJobRegistryInterface'

  Dawid\CronBundle\CronJobRunnerInterface:
    tags: [ 'cron.job' ]
