services:
  App\Core\Cron\CronJobRunner\Config\Config:
    class: 'App\Core\Cron\CronJobRunner\Config\Config'
    public: false
    arguments:
      $commands: [ ]

  App\Core\Cron\CronJobRunner\JobScheduler:
    class: 'App\Core\Cron\CronJobRunner\JobScheduler'
    public: false

  App\Core\Cron\CronJobRunner\CommandRunner:
    class: 'App\Core\Cron\CronJobRunner\CommandRunner'
    public: false
    arguments:
      $kernel: '@kernel'

  App\Core\Cron\CronJobRunner\Cron:
    class: 'App\Core\Cron\CronJobRunner\Cron'
    public: false
    arguments:
      $config: '@App\Core\Cron\CronJobRunner\Config\Config'
      $commandRunner: '@App\Core\Cron\CronJobRunner\CommandRunner'
      $jobScheduler: '@App\Core\Cron\CronJobRunner\JobScheduler'

  App\Core\Cron\Command\CronRunnerCommand:
    class: 'App\Core\Cron\Command\CronRunnerCommand'
    tags:
      - { name: 'console.command', command: 'cron:run' }
    arguments:
      $runner: '@App\Core\Cron\CronJobRunner\Cron'
      $logger: '@logger'
