services:

  Dawid\CronBundle\JobScheduler:
    class: 'Dawid\CronBundle\JobScheduler'
    public: false

  Dawid\CronBundle\CronJobRegistry:
    class: 'Dawid\CronBundle\CronJobRegistry'
    arguments:
      - !tagged_iterator { tag: 'cron.job' }

  Dawid\CronBundle\CronJobRegistryInterface: '@Dawid\CronBundle\CronJobRegistry'

  Dawid\CronBundle\Cron:
    class: 'Dawid\CronBundle\Cron'
    public: false
    arguments:
      $jobScheduler: '@Dawid\CronBundle\CronJobRegistryInterface'

  Dawid\CronBundle\Command\CronRunnerCommand:
    class: 'Dawid\CronBundle\Command\CronRunnerCommand'
    tags:
      - { name: 'console.command', command: 'cron:run' }
    arguments:
      $runner: '@Dawid\CronBundle\Cron'
      $logger: '@logger'