services:
  Dawid\CronBundle\CronJobRegistry:
    class: 'Dawid\CronBundle\CronJobRegistry'
    arguments:
      - !tagged_iterator { tag: 'cron.job' }

  cron_doctrine_passed_jobs_repository:
    class: 'Dawid\CronBundle\Extension\Doctrine\DoctrinePassedJobsRepository'
    arguments:
      $em: '@doctrine.orm.entity_manager'

  Dawid\CronBundle\CronJobRegistryInterface: '@cron_doctrine_passed_jobs_repository'

  Dawid\CronBundle\CronJobScheduler:
    class: 'Dawid\CronBundle\CronJobScheduler'
    public: false
    arguments:
      $passedJobsRepository: '@Dawid\CronBundle\CronJobRegistryInterface'

  Dawid\CronBundle\Cron:
    class: 'Dawid\CronBundle\Cron'
    public: false
    arguments:
      $scheduler: '@Dawid\CronBundle\CronJobScheduler'
      $registry: '@Dawid\CronBundle\CronJobRegistry'

  Dawid\CronBundle\Command\CronRunnerCommand:
    class: 'Dawid\CronBundle\Command\CronRunnerCommand'
    tags:
      - { name: 'console.command', command: 'cron:run' }
    arguments:
      $runner: '@Dawid\CronBundle\Cron'
      $logger: '@logger'