services:

  Dawid\CronBundle\JobScheduler:
    class: 'Dawid\CronBundle\JobScheduler'
    public: false

  Dawid\CronBundle\CronJobRegistry:
    class: 'Dawid\CronBundle\CronJobRegistry'
    arguments:
      - !tagged_iterator { tag: 'cron.job' }

  Dawid\CronBundle\CronJobRegistryInterface: '@Dawid\CronBundle\CronJobRegistry'

  cron_doctrine_passed_jobs_repository:
    class: 'Dawid\CronBundle\Extension\Doctrine\DoctrinePassedJobsRepository'
    arguments:
      $em: '@doctrine.orm.entity_manager'

  Dawid\CronBundle\PassedJobsInterfaceRepository: '@cron_doctrine_passed_jobs_repository'

  Dawid\CronBundle\Cron:
    class: 'Dawid\CronBundle\Cron'
    public: false
    arguments:
      $passedJobsInterfaceRepository: '@Dawid\CronBundle\PassedJobsInterfaceRepository'

  Dawid\CronBundle\Command\CronRunnerCommand:
    class: 'Dawid\CronBundle\Command\CronRunnerCommand'
    tags:
      - { name: 'console.command', command: 'cron:run' }
    arguments:
      $runner: '@Dawid\CronBundle\Cron'
      $logger: '@logger'